# Generated by Django 4.1.7 on 2023-03-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('ND 1', 'ND 1'), ('ND 2', 'ND 2'), ('HND 1', 'HND 1'), ('HND 2', 'HND 2')], max_length=50)),
                ('program', models.CharField(blank=True, choices=[('FT', 'FULL TIME'), ('PT', 'PART TIME')], max_length=50, null=True)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
                ('classes', models.ManyToManyField(related_name='course_classes', to='timetable.class')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('period', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=50)),
                ('semester', models.CharField(choices=[('FIRST SEMESTER', 'FIRST SEMESTER'), ('SECOND SEMESTER', 'SECOND SEMESTER'), ('THIRD SEMESTER', 'THIRD SEMESTER')], max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_class', to='timetable.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_course', to='timetable.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_dep', to='timetable.department')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_hall', to='timetable.hall')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_dep', to='timetable.department'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_dep', to='timetable.department'),
        ),
    ]
