# Generated by Django 4.1.7 on 2023-03-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hall',
        ),
    ]
