# Generated by Django 4.1.7 on 2023-04-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_rename_size_hall_capacity_hall_hall_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='timetable.course'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_class', to='timetable.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('ND I', 'ND I'), ('ND II', 'ND II'), ('HND I', 'HND I'), ('HND II', 'HND II')], max_length=50),
        ),
    ]
