# Generated by Django 4.1.7 on 2023-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_course_classes_class_courses_schedule_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(blank=True, choices=[('FIRST SEMESTER', 'FIRST SEMESTER'), ('SECOND SEMESTER', 'SECOND SEMESTER'), ('THIRD SEMESTER', 'THIRD SEMESTER')], max_length=50, null=True),
        ),
    ]
