# Generated by Django 4.1.7 on 2023-04-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.day'),
        ),
    ]
