# Generated by Django 4.1.7 on 2023-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_schedule_day_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
