# Generated by Django 4.1.7 on 2023-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_alter_class_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.CharField(default='PBE', max_length=50),
        ),
    ]
