# Generated by Django 4.1.7 on 2023-06-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_course_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_hall', to='timetable.hall')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_schedule', to='timetable.schedule')),
            ],
        ),
    ]
