# Generated by Django 4.1.7 on 2023-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_halldistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
                ('halls', models.ManyToManyField(related_name='block_hall', to='timetable.hall')),
            ],
        ),
    ]
