# Generated by Django 4.1.7 on 2023-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_hallblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
