# Generated by Django 4.1.7 on 2023-10-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='max_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hall',
            name='min_courses',
            field=models.IntegerField(default=0),
        ),
    ]
