# Generated by Django 4.1.7 on 2023-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_hall_max_students_hall_min_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='working_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
