# Generated by Django 4.1.7 on 2023-10-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_hall_working_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.hall')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='HallDistribution',
        ),
        migrations.AddField(
            model_name='distribution',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.distributionitem'),
        ),
    ]
