# Generated by Django 4.1.7 on 2023-10-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_remove_distribution_items_distribution_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='day',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='period',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
